apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  type: NodePort
  selector:
    app: service3
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007